import fs from "node:fs/promises";
import path from "node:path";
import type { AstroIntegration } from "astro";

/**
 * Appends 301 redirects from the legacy date-prefixed article URLs
 * (`/YYYY/MM/<slug>/`) to the canonical flat URLs (`/<slug>`).
 *
 * The legacy shape matches the URL pattern produced by the old "engineer"
 * static site generator and the deleted `src/pages/[...slug].astro` route.
 * This integration runs after Astro's build copies `public/_redirects` into
 * `dist/`, so existing redirect rules are preserved.
 *
 * Article frontmatter is read directly from the filesystem rather than via
 * `getCollection` because Astro integrations are loaded before the
 * `astro:content` virtual module is available.
 */
export function articleRedirects(): AstroIntegration {
  return {
    name: "article-redirects",
    hooks: {
      "astro:build:done": async ({ dir, logger }) => {
        const articlesDir = path.resolve("src/content/articles");
        const files = await collectArticleFiles(articlesDir);

        const showDrafts = process.env.SHOW_DRAFTS === "1";
        const lines: string[] = [];

        for (const file of files) {
          const text = await fs.readFile(file, "utf8");
          const fm = parseFrontmatter(text);
          if (!fm) continue;
          if (fm.draft === "true" && !showDrafts) continue;

          const slug = fm.slug;
          const dateStr = fm.date;
          if (!slug || !dateStr) continue;

          const date = new Date(dateStr);
          if (Number.isNaN(date.getTime())) continue;

          const year = date.getUTCFullYear();
          const month = String(date.getUTCMonth() + 1).padStart(2, "0");

          lines.push(`/${year}/${month}/${slug}/  /${slug}  301`);
        }

        lines.sort();

        const outPath = path.join(dir.pathname, "_redirects");
        let existing = "";
        try {
          existing = await fs.readFile(outPath, "utf8");
        } catch {
          // No existing _redirects; that's fine.
        }

        const banner =
          "\n# --- generated by article-redirects (legacy date-prefixed URLs) ---\n";
        const trailingNewline =
          existing === "" || existing.endsWith("\n") ? "" : "\n";
        const content = `${existing}${trailingNewline}${banner}${lines.join("\n")}\n`;

        await fs.writeFile(outPath, content, "utf8");
        logger.info(
          `Wrote ${lines.length} legacy article redirects to ${outPath}`,
        );
      },
    },
  };
}

async function collectArticleFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: string) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (
        entry.isFile() &&
        !entry.name.startsWith("_") &&
        (entry.name.endsWith(".md") || entry.name.endsWith(".mdx"))
      ) {
        out.push(full);
      }
    }
  }
  await walk(root);
  return out;
}

/**
 * Minimal YAML frontmatter parser for the fields we need (slug, date, draft).
 * Avoids adding gray-matter as a dependency.
 */
function parseFrontmatter(text: string): Record<string, string> | null {
  if (!text.startsWith("---")) return null;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return null;
  const block = text.slice(3, end);
  const result: Record<string, string> = {};
  for (const rawLine of block.split("\n")) {
    const line = rawLine.trimEnd();
    // Only look at top-level key: value pairs (skip nested fields like engineer.url).
    const m = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    let value = m[2].trim();
    if (
      (value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))
    ) {
      value = value.slice(1, -1);
    }
    result[m[1]] = value;
  }
  return result;
}
